#*****************************************************************************************
# Vivado (TM) v2019.1.3_AR72746 (64-bit)
#
# vu47p_project.tcl: Tcl script for re-creating project 'vu47p_test'
#
# Generated by Vivado on Fri Jun 19 15:17:48 PDT 2026
# IP Build 2633630 on Wed Sep  4 12:30:14 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (vu47p_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/axis_traffic_gen_checker.sv"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_defines.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_and.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_array_reverse.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/hard/bsg_async_fifo.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_async/bsg_async_ptr_gray.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_circular_ptr.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_counter_clear_up.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_counter_set_down.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_dff_en.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_dff_reset.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/bsg_fifo_1r1w_small_hardened.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_tracker.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/hard/bsg_launch_sync_sync.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync_synth.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_synth.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_misc/bsg_mux.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_one_fifo.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_parallel_in_serial_out.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/bsg_reset_chain.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/bsg_reset_module.sv"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_round_robin_1_to_n.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_serial_in_parallel_out_full.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/hard/bsg_sync_sync.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/basejump_stl_bigblade/bsg_dataflow/bsg_two_fifo.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/dma_width_converter.sv"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/top.v"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/v/dma_width_converter_nopatch.sv"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xci/RIFL_0/RIFL_0.xci"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xci/RIFL_1/RIFL_1.xci"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xci/RIFL_2/RIFL_2.xci"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xci/RIFL_3/RIFL_3.xci"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xdc/io.xdc"
#    "/home/paul/playground/rifl_standalone/bsg_hammerhead/main_board/vu47p_rifl_standalone/xdc/impl.tcl"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "vu47p_test"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "vu47p_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vu47p_test"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu47p-fsvh2892-3-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvu47p-fsvh2892-3-e" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "23" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "23" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "23" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "23" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "23" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "23" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "23" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/common/RIFL/ip_repo"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/v/axis_traffic_gen_checker.sv"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_defines.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_and.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_array_reverse.v"] \
 [file normalize "${origin_dir}/v/hard/bsg_async_fifo.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_async/bsg_async_ptr_gray.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_circular_ptr.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_counter_clear_up.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_counter_set_down.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_dff_en.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_dff_reset.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small.v"] \
 [file normalize "${origin_dir}/v/bsg_fifo_1r1w_small_hardened.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_tracker.v"] \
 [file normalize "${origin_dir}/v/hard/bsg_launch_sync_sync.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync_synth.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_synth.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_misc/bsg_mux.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_one_fifo.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_parallel_in_serial_out.v"] \
 [file normalize "${origin_dir}/v/bsg_reset_chain.v"] \
 [file normalize "${origin_dir}/v/bsg_reset_module.sv"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_round_robin_1_to_n.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_serial_in_parallel_out_full.v"] \
 [file normalize "${origin_dir}/v/hard/bsg_sync_sync.v"] \
 [file normalize "${origin_dir}/basejump_stl_bigblade/bsg_dataflow/bsg_two_fifo.v"] \
 [file normalize "${origin_dir}/v/dma_width_converter.sv"] \
 [file normalize "${origin_dir}/v/top.v"] \
 [file normalize "${origin_dir}/v/dma_width_converter_nopatch.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/v/axis_traffic_gen_checker.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_defines.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_and.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_array_reverse.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/hard/bsg_async_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_async/bsg_async_ptr_gray.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_circular_ptr.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_counter_clear_up.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_counter_set_down.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_dff_en.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_dff_reset.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/bsg_fifo_1r1w_small_hardened.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_1r1w_small_unhardened.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_fifo_tracker.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/hard/bsg_launch_sync_sync.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_sync_synth.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_mem/bsg_mem_1r1w_synth.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_misc/bsg_mux.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_one_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_parallel_in_serial_out.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/bsg_reset_chain.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/bsg_reset_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_round_robin_1_to_n.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_serial_in_parallel_out_full.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/hard/bsg_sync_sync.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/basejump_stl_bigblade/bsg_dataflow/bsg_two_fifo.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/dma_width_converter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/top.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/v/dma_width_converter_nopatch.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/xci/RIFL_0/RIFL_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/xci/RIFL_0/RIFL_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/xci/RIFL_1/RIFL_1.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/xci/RIFL_1/RIFL_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/xci/RIFL_2/RIFL_2.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/xci/RIFL_2/RIFL_2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/xci/RIFL_3/RIFL_3.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/xci/RIFL_3/RIFL_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/xdc/io.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/xdc/io.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/xdc/impl.tcl"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/xdc/impl.tcl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "TCL" -objects $file_obj
set_property -name "used_in" -value "implementation" -objects $file_obj
set_property -name "used_in_simulation" -value "0" -objects $file_obj
set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcvu47p-fsvh2892-3-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD design_ila_axis_debug
proc cr_bd_design_ila_axis_debug { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name design_ila_axis_debug

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:ila:6.2\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set clk [ create_bd_port -dir I -type clk clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {400000000} \
 ] $clk
  set compensate [ create_bd_port -dir I compensate ]
  set local_fc [ create_bd_port -dir I -from 3 -to 0 local_fc ]
  set m_axis_counter [ create_bd_port -dir I -from 15 -to 0 m_axis_counter ]
  set m_axis_counter_last [ create_bd_port -dir I -from 15 -to 0 m_axis_counter_last ]
  set m_axis_counter_tkeep [ create_bd_port -dir I -from 15 -to 0 m_axis_counter_tkeep ]
  set remote_fc [ create_bd_port -dir I -from 3 -to 0 remote_fc ]
  set rx_aligned [ create_bd_port -dir I -from 3 -to 0 rx_aligned ]
  set rx_error [ create_bd_port -dir I -from 3 -to 0 rx_error ]
  set rx_pause_request [ create_bd_port -dir I -from 3 -to 0 rx_pause_request ]
  set rx_retrans_request [ create_bd_port -dir I -from 3 -to 0 rx_retrans_request ]
  set rx_up [ create_bd_port -dir I -from 3 -to 0 rx_up ]
  set s_axis_counter [ create_bd_port -dir I -from 15 -to 0 s_axis_counter ]
  set s_axis_counter_last [ create_bd_port -dir I -from 15 -to 0 s_axis_counter_last ]
  set s_axis_counter_tkeep [ create_bd_port -dir I -from 15 -to 0 s_axis_counter_tkeep ]
  set tx_state_init [ create_bd_port -dir I -from 3 -to 0 tx_state_init ]
  set tx_state_normal [ create_bd_port -dir I -from 3 -to 0 tx_state_normal ]
  set tx_state_pause [ create_bd_port -dir I -from 3 -to 0 tx_state_pause ]
  set tx_state_retrans [ create_bd_port -dir I -from 3 -to 0 tx_state_retrans ]
  set tx_state_send_pause [ create_bd_port -dir I -from 3 -to 0 tx_state_send_pause ]
  set tx_state_send_retrans [ create_bd_port -dir I -from 3 -to 0 tx_state_send_retrans ]

  # Create instance: ila_0, and set properties
  set ila_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ila:6.2 ila_0 ]
  set_property -dict [ list \
   CONFIG.ALL_PROBE_SAME_MU_CNT {2} \
   CONFIG.C_ENABLE_ILA_AXI_MON {false} \
   CONFIG.C_EN_STRG_QUAL {1} \
   CONFIG.C_MONITOR_TYPE {Native} \
   CONFIG.C_NUM_OF_PROBES {20} \
   CONFIG.C_PROBE0_MU_CNT {2} \
   CONFIG.C_PROBE0_WIDTH {16} \
   CONFIG.C_PROBE10_WIDTH {4} \
   CONFIG.C_PROBE11_WIDTH {4} \
   CONFIG.C_PROBE12_WIDTH {4} \
   CONFIG.C_PROBE13_WIDTH {4} \
   CONFIG.C_PROBE14_WIDTH {4} \
   CONFIG.C_PROBE15_WIDTH {4} \
   CONFIG.C_PROBE16_WIDTH {4} \
   CONFIG.C_PROBE17_WIDTH {4} \
   CONFIG.C_PROBE18_WIDTH {4} \
   CONFIG.C_PROBE19_WIDTH {1} \
   CONFIG.C_PROBE1_MU_CNT {2} \
   CONFIG.C_PROBE1_WIDTH {16} \
   CONFIG.C_PROBE2_MU_CNT {2} \
   CONFIG.C_PROBE2_WIDTH {16} \
   CONFIG.C_PROBE3_MU_CNT {2} \
   CONFIG.C_PROBE3_WIDTH {16} \
   CONFIG.C_PROBE4_MU_CNT {2} \
   CONFIG.C_PROBE4_WIDTH {16} \
   CONFIG.C_PROBE5_MU_CNT {2} \
   CONFIG.C_PROBE5_WIDTH {16} \
   CONFIG.C_PROBE6_MU_CNT {2} \
   CONFIG.C_PROBE6_WIDTH {4} \
   CONFIG.C_PROBE7_MU_CNT {2} \
   CONFIG.C_PROBE7_WIDTH {4} \
   CONFIG.C_PROBE8_MU_CNT {2} \
   CONFIG.C_PROBE8_WIDTH {4} \
   CONFIG.C_PROBE9_WIDTH {4} \
 ] $ila_0

  # Create port connections
  connect_bd_net -net clk_1 [get_bd_ports clk] [get_bd_pins ila_0/clk]
  connect_bd_net -net compensate_1 [get_bd_ports compensate] [get_bd_pins ila_0/probe19]
  connect_bd_net -net local_fc_1 [get_bd_ports local_fc] [get_bd_pins ila_0/probe17]
  connect_bd_net -net m_axis_counter_1 [get_bd_ports m_axis_counter] [get_bd_pins ila_0/probe0]
  connect_bd_net -net m_axis_counter_last_1 [get_bd_ports m_axis_counter_last] [get_bd_pins ila_0/probe2]
  connect_bd_net -net m_axis_counter_tkeep_1 [get_bd_ports m_axis_counter_tkeep] [get_bd_pins ila_0/probe4]
  connect_bd_net -net remote_fc_1 [get_bd_ports remote_fc] [get_bd_pins ila_0/probe18]
  connect_bd_net -net rx_aligned_1 [get_bd_ports rx_aligned] [get_bd_pins ila_0/probe13]
  connect_bd_net -net rx_error_1 [get_bd_ports rx_error] [get_bd_pins ila_0/probe14]
  connect_bd_net -net rx_pause_request_1 [get_bd_ports rx_pause_request] [get_bd_pins ila_0/probe15]
  connect_bd_net -net rx_retrans_request_1 [get_bd_ports rx_retrans_request] [get_bd_pins ila_0/probe16]
  connect_bd_net -net rx_up_1 [get_bd_ports rx_up] [get_bd_pins ila_0/probe12]
  connect_bd_net -net s_axis_counter_1 [get_bd_ports s_axis_counter] [get_bd_pins ila_0/probe1]
  connect_bd_net -net s_axis_counter_last_1 [get_bd_ports s_axis_counter_last] [get_bd_pins ila_0/probe3]
  connect_bd_net -net s_axis_counter_tkeep_1 [get_bd_ports s_axis_counter_tkeep] [get_bd_pins ila_0/probe5]
  connect_bd_net -net tx_state_init_1 [get_bd_ports tx_state_init] [get_bd_pins ila_0/probe6]
  connect_bd_net -net tx_state_normal_1 [get_bd_ports tx_state_normal] [get_bd_pins ila_0/probe11]
  connect_bd_net -net tx_state_pause_1 [get_bd_ports tx_state_pause] [get_bd_pins ila_0/probe8]
  connect_bd_net -net tx_state_retrans_1 [get_bd_ports tx_state_retrans] [get_bd_pins ila_0/probe10]
  connect_bd_net -net tx_state_send_pause_1 [get_bd_ports tx_state_send_pause] [get_bd_pins ila_0/probe7]
  connect_bd_net -net tx_state_send_retrans_1 [get_bd_ports tx_state_send_retrans] [get_bd_pins ila_0/probe9]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_ila_axis_debug()
cr_bd_design_ila_axis_debug ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_ila_axis_debug.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_ila_axis_debug.bd ] 



# Proc to create BD design_vio_rifl_rst
proc cr_bd_design_vio_rifl_rst { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name design_vio_rifl_rst

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:vio:3.0\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set clk [ create_bd_port -dir I -type clk clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {100000000} \
 ] $clk
  set rst [ create_bd_port -dir O -from 0 -to 0 rst ]

  # Create instance: vio_0, and set properties
  set vio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:vio:3.0 vio_0 ]
  set_property -dict [ list \
   CONFIG.C_EN_PROBE_IN_ACTIVITY {0} \
   CONFIG.C_NUM_PROBE_IN {0} \
 ] $vio_0

  # Create port connections
  connect_bd_net -net clk_1 [get_bd_ports clk] [get_bd_pins vio_0/clk]
  connect_bd_net -net vio_0_probe_out0 [get_bd_ports rst] [get_bd_pins vio_0/probe_out0]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_vio_rifl_rst()
cr_bd_design_vio_rifl_rst ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_vio_rifl_rst.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_vio_rifl_rst.bd ] 



# Proc to create BD design_vio_rifl_bist
proc cr_bd_design_vio_rifl_bist { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name design_vio_rifl_bist

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:vio:3.0\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set clk [ create_bd_port -dir I -type clk clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {250000000} \
 ] $clk
  set probe_in0 [ create_bd_port -dir I probe_in0 ]
  set probe_in1 [ create_bd_port -dir I probe_in1 ]
  set probe_in2 [ create_bd_port -dir I probe_in2 ]
  set probe_in3 [ create_bd_port -dir I probe_in3 ]
  set probe_in4 [ create_bd_port -dir I probe_in4 ]
  set probe_in5 [ create_bd_port -dir I -from 3 -to 0 probe_in5 ]
  set probe_in6 [ create_bd_port -dir I -from 63 -to 0 probe_in6 ]
  set probe_in7 [ create_bd_port -dir I -from 63 -to 0 probe_in7 ]
  set probe_in8 [ create_bd_port -dir I -from 63 -to 0 probe_in8 ]
  set probe_in9 [ create_bd_port -dir I -from 63 -to 0 probe_in9 ]
  set probe_in10 [ create_bd_port -dir I -from 63 -to 0 probe_in10 ]
  set probe_in11 [ create_bd_port -dir I -from 31 -to 0 probe_in11 ]
  set probe_in12 [ create_bd_port -dir I -from 63 -to 0 probe_in12 ]
  set probe_in13 [ create_bd_port -dir I -from 63 -to 0 probe_in13 ]
  set probe_in14 [ create_bd_port -dir I probe_in14 ]
  set probe_in15 [ create_bd_port -dir I probe_in15 ]
  set probe_out0 [ create_bd_port -dir O -from 0 -to 0 probe_out0 ]
  set probe_out1 [ create_bd_port -dir O -from 0 -to 0 probe_out1 ]
  set probe_out2 [ create_bd_port -dir O -from 0 -to 0 probe_out2 ]
  set probe_out3 [ create_bd_port -dir O -from 0 -to 0 probe_out3 ]
  set probe_out4 [ create_bd_port -dir O -from 0 -to 0 probe_out4 ]
  set probe_out5 [ create_bd_port -dir O -from 1 -to 0 probe_out5 ]
  set probe_out6 [ create_bd_port -dir O -from 15 -to 0 probe_out6 ]
  set probe_out7 [ create_bd_port -dir O -from 15 -to 0 probe_out7 ]
  set probe_out8 [ create_bd_port -dir O -from 15 -to 0 probe_out8 ]
  set probe_out9 [ create_bd_port -dir O -from 15 -to 0 probe_out9 ]
  set probe_out10 [ create_bd_port -dir O -from 63 -to 0 probe_out10 ]
  set probe_out11 [ create_bd_port -dir O -from 31 -to 0 probe_out11 ]

  # Create instance: vio_0, and set properties
  set vio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:vio:3.0 vio_0 ]
  set_property -dict [ list \
   CONFIG.C_NUM_PROBE_IN {16} \
   CONFIG.C_NUM_PROBE_OUT {12} \
   CONFIG.C_PROBE_OUT10_INIT_VAL {0x0000000002000000} \
   CONFIG.C_PROBE_OUT10_WIDTH {64} \
   CONFIG.C_PROBE_OUT11_INIT_VAL {0x00000000} \
   CONFIG.C_PROBE_OUT11_WIDTH {32} \
   CONFIG.C_PROBE_OUT3_WIDTH {1} \
   CONFIG.C_PROBE_OUT4_INIT_VAL {0x0} \
   CONFIG.C_PROBE_OUT4_WIDTH {1} \
   CONFIG.C_PROBE_OUT5_INIT_VAL {0x0} \
   CONFIG.C_PROBE_OUT5_WIDTH {2} \
   CONFIG.C_PROBE_OUT6_INIT_VAL {0x0021} \
   CONFIG.C_PROBE_OUT6_WIDTH {16} \
   CONFIG.C_PROBE_OUT7_INIT_VAL {0x0001} \
   CONFIG.C_PROBE_OUT7_WIDTH {16} \
   CONFIG.C_PROBE_OUT8_INIT_VAL {0x0021} \
   CONFIG.C_PROBE_OUT8_WIDTH {16} \
   CONFIG.C_PROBE_OUT9_INIT_VAL {0x0000} \
   CONFIG.C_PROBE_OUT9_WIDTH {16} \
 ] $vio_0

  # Create port connections
  connect_bd_net -net clk_1 [get_bd_ports clk] [get_bd_pins vio_0/clk]
  connect_bd_net -net probe_in0_1 [get_bd_ports probe_in0] [get_bd_pins vio_0/probe_in0]
  connect_bd_net -net probe_in10_1 [get_bd_ports probe_in10] [get_bd_pins vio_0/probe_in10]
  connect_bd_net -net probe_in11_1 [get_bd_ports probe_in11] [get_bd_pins vio_0/probe_in11]
  connect_bd_net -net probe_in12_1 [get_bd_ports probe_in12] [get_bd_pins vio_0/probe_in12]
  connect_bd_net -net probe_in13_1 [get_bd_ports probe_in13] [get_bd_pins vio_0/probe_in13]
  connect_bd_net -net probe_in14_1 [get_bd_ports probe_in14] [get_bd_pins vio_0/probe_in14]
  connect_bd_net -net probe_in15_1 [get_bd_ports probe_in15] [get_bd_pins vio_0/probe_in15]
  connect_bd_net -net probe_in1_1 [get_bd_ports probe_in1] [get_bd_pins vio_0/probe_in1]
  connect_bd_net -net probe_in2_1 [get_bd_ports probe_in2] [get_bd_pins vio_0/probe_in2]
  connect_bd_net -net probe_in3_1 [get_bd_ports probe_in3] [get_bd_pins vio_0/probe_in3]
  connect_bd_net -net probe_in4_1 [get_bd_ports probe_in4] [get_bd_pins vio_0/probe_in4]
  connect_bd_net -net probe_in5_1 [get_bd_ports probe_in5] [get_bd_pins vio_0/probe_in5]
  connect_bd_net -net probe_in6_1 [get_bd_ports probe_in6] [get_bd_pins vio_0/probe_in6]
  connect_bd_net -net probe_in7_1 [get_bd_ports probe_in7] [get_bd_pins vio_0/probe_in7]
  connect_bd_net -net probe_in8_1 [get_bd_ports probe_in8] [get_bd_pins vio_0/probe_in8]
  connect_bd_net -net probe_in9_1 [get_bd_ports probe_in9] [get_bd_pins vio_0/probe_in9]
  connect_bd_net -net vio_0_probe_out0 [get_bd_ports probe_out0] [get_bd_pins vio_0/probe_out0]
  connect_bd_net -net vio_0_probe_out1 [get_bd_ports probe_out1] [get_bd_pins vio_0/probe_out1]
  connect_bd_net -net vio_0_probe_out2 [get_bd_ports probe_out2] [get_bd_pins vio_0/probe_out2]
  connect_bd_net -net vio_0_probe_out3 [get_bd_ports probe_out3] [get_bd_pins vio_0/probe_out3]
  connect_bd_net -net vio_0_probe_out4 [get_bd_ports probe_out4] [get_bd_pins vio_0/probe_out4]
  connect_bd_net -net vio_0_probe_out5 [get_bd_ports probe_out5] [get_bd_pins vio_0/probe_out5]
  connect_bd_net -net vio_0_probe_out6 [get_bd_ports probe_out6] [get_bd_pins vio_0/probe_out6]
  connect_bd_net -net vio_0_probe_out7 [get_bd_ports probe_out7] [get_bd_pins vio_0/probe_out7]
  connect_bd_net -net vio_0_probe_out8 [get_bd_ports probe_out8] [get_bd_pins vio_0/probe_out8]
  connect_bd_net -net vio_0_probe_out9 [get_bd_ports probe_out9] [get_bd_pins vio_0/probe_out9]
  connect_bd_net -net vio_0_probe_out10 [get_bd_ports probe_out10] [get_bd_pins vio_0/probe_out10]
  connect_bd_net -net vio_0_probe_out11 [get_bd_ports probe_out11] [get_bd_pins vio_0/probe_out11]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_vio_rifl_bist()
cr_bd_design_vio_rifl_bist ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_vio_rifl_bist.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_vio_rifl_bist.bd ] 



# Proc to create BD firmware_bd
proc cr_bd_firmware_bd { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name firmware_bd

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:util_ds_buf:2.1\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set ext_refclk [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 ext_refclk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {200000000} \
   ] $ext_refclk


  # Create ports
  set core_clk [ create_bd_port -dir O -type clk core_clk ]
  set init_clk [ create_bd_port -dir O -type clk init_clk ]

  # Create instance: clk_wiz_0, and set properties
  set clk_wiz_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0 ]
  set_property -dict [ list \
   CONFIG.CLKOUT1_JITTER {103.903} \
   CONFIG.CLKOUT1_PHASE_ERROR {80.662} \
   CONFIG.CLKOUT2_JITTER {87.134} \
   CONFIG.CLKOUT2_PHASE_ERROR {80.662} \
   CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {250.000} \
   CONFIG.CLKOUT2_USED {true} \
   CONFIG.MMCM_CLKFBOUT_MULT_F {6.250} \
   CONFIG.MMCM_CLKOUT0_DIVIDE_F {12.500} \
   CONFIG.MMCM_CLKOUT1_DIVIDE {5} \
   CONFIG.NUM_OUT_CLKS {2} \
   CONFIG.PRIM_SOURCE {Global_buffer} \
   CONFIG.USE_LOCKED {false} \
   CONFIG.USE_RESET {false} \
 ] $clk_wiz_0

  # Create instance: util_ds_buf_1, and set properties
  set util_ds_buf_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.1 util_ds_buf_1 ]
  set_property -dict [ list \
   CONFIG.C_BUF_TYPE {IBUFDS} \
 ] $util_ds_buf_1

  # Create instance: util_ds_buf_2, and set properties
  set util_ds_buf_2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.1 util_ds_buf_2 ]
  set_property -dict [ list \
   CONFIG.C_BUF_TYPE {BUFG} \
 ] $util_ds_buf_2

  # Create interface connections
  connect_bd_intf_net -intf_net ext_refclk_1 [get_bd_intf_ports ext_refclk] [get_bd_intf_pins util_ds_buf_1/CLK_IN_D]

  # Create port connections
  connect_bd_net -net clk_wiz_0_clk_out1 [get_bd_ports init_clk] [get_bd_pins clk_wiz_0/clk_out1]
  connect_bd_net -net clk_wiz_0_clk_out2 [get_bd_ports core_clk] [get_bd_pins clk_wiz_0/clk_out2]
  connect_bd_net -net util_ds_buf_1_IBUF_OUT [get_bd_pins util_ds_buf_1/IBUF_OUT] [get_bd_pins util_ds_buf_2/BUFG_I]
  connect_bd_net -net util_ds_buf_2_BUFG_O [get_bd_pins clk_wiz_0/clk_in1] [get_bd_pins util_ds_buf_2/BUFG_O]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_firmware_bd()
cr_bd_firmware_bd ""
set_property REGISTERED_WITH_MANAGER "1" [get_files firmware_bd.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files firmware_bd.bd ] 



# Proc to create BD design_vio_global_rst
proc cr_bd_design_vio_global_rst { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name design_vio_global_rst

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:vio:3.0\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set clk [ create_bd_port -dir I -type clk clk ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {100000000} \
 ] $clk
  set rst [ create_bd_port -dir O -from 0 -to 0 rst ]

  # Create instance: vio_0, and set properties
  set vio_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:vio:3.0 vio_0 ]
  set_property -dict [ list \
   CONFIG.C_EN_PROBE_IN_ACTIVITY {0} \
   CONFIG.C_NUM_PROBE_IN {0} \
 ] $vio_0

  # Create port connections
  connect_bd_net -net clk_1 [get_bd_ports clk] [get_bd_pins vio_0/clk]
  connect_bd_net -net vio_0_probe_out0 [get_bd_ports rst] [get_bd_pins vio_0/probe_out0]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_vio_global_rst()
cr_bd_design_vio_global_rst ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_vio_global_rst.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_vio_global_rst.bd ] 

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu47p-fsvh2892-3-e -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvu47p-fsvh2892-3-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu47p-fsvh2892-3-e -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvu47p-fsvh2892-3-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
